yglukhov/rod

- rod/viewport.nim
> fixed public method

- rod/component/particle_emitter.nim
- particle attractor added;
- oneShot behavior in particle emitter added;
> Particle system changes

- .gitignore
- editor/nakefile.nim
- nakefile.nim
- rod/component.nim
- rod/component/mesh_component.nim
- rod/component/sprite.nim
- rod/edit_view.nim
- rod/node.nim
- rod/outline_view.nim
- rod/ray.nim
- added rayCast for sprite and mesh component
- added objects  selection in editor
- added expandBranch and collapseBranch for OutlineView
> - added rayCast for sprite and mesh component

- rod/viewport.nim
add onEnter and onExit view handling
> add onEnter and onExit event's

- after_effects_export/nakefile.nim
add windows default path for after effects
> add win default ae path

- rod/component/sprite.nim
> fix import

- after_effects_export/after_effects.nim
- after_effects_export/rod_export.nim
- rod/component/visual_modifier.nim
> Blending export from AfterEffects

- rod/rod_types.nim
- rod/viewport.nim
fix bug with delta time, caused by re-adding sceneView to window
> fix delta time

- rod/component/particle_helpers.nim
- rod/component/particle_system.nim
- rod/material/shader.nim
- rod/tools/debug_draw.nim
- rod/viewport.nim
- added debug info to particle attractors
- now shader create if context exist
- added debugDraw primitives (line, box, circle, arrow)
> Particle debug info

- rod/tools/imgtool.nim
> fix extrusion, add bleeding

- editor/res/Jsondata/ps.json
- rod/component.nim
- rod/component/blink.nim
- rod/component/blur_component.nim
- rod/component/camera.nim
- rod/component/channel_levels.nim
- rod/component/clipping_rect_component.nim
- rod/component/fxaa_post.nim
- rod/component/light.nim
- rod/component/mesh_component.nim
- rod/component/node_selector.nim
- rod/component/overlay.nim
- rod/component/particle_emitter.nim
- rod/component/particle_helpers.nim
- rod/component/particle_system.nim
- rod/component/solid.nim
- rod/component/sprite.nim
- rod/component/text_component.nim
- rod/component/tracer.nim
- rod/component/trail.nim
- rod/component/ui_component.nim
- rod/component/visual_modifier.nim
- rod/inspector_view.nim
- rod/material/shader.nim
- rod/node.nim
- rod/rod_types.nim
- rod/tools/debug_draw.nim
- Now components are stored in seq
> Components order

- rod/component/ui_component.nim
fix intersects checking for UIComponent
> fix intersect checking

- rod/component/text_component.nim
add deserialization for font shadow by shadowX, shadowY
> font shadow deserialization

- rod/component/text_component.nim
> Added text soft shadow

- rod/component/sprite.nim
add offset getter for sprite component
> sprite offset

- rod/component.nim
- rod/component/blur_component.nim
- rod/component/channel_levels.nim
- rod/component/overlay.nim
- rod/component/particle_emitter.nim
- rod/component/particle_helpers.nim
- rod/component/particle_system.nim
- rod/component/visual_modifier.nim
- rod/inspector_view.nim
- New expanding view for components
> New expanding view for components

- rod/tools/rodasset.nim
add path converting in rodasset from "example/somedir\some.file" to "example\somedir\some.file"
> fix paths in rodasset

- rod/component/sprite.nim
sprite minPoint and maxPoint bounds was inversed
> fix prite bounds

- rod/component/particle_system.nim
move encoding func from fragment to vertex shader.
> Fix particle float encoding.

- after_effects_export/after_effects.nim
- after_effects_export/rod_export.nim
- rod/node.nim
- rod/rod_types.nim
dirty  exporting support xyz rotation from AE
> 3d rotation from AE

- rod/tools/rodasset/asset_cache.nim
Workaround for "Access Denied" Exception during file replacing on Windows.
> Workaround for "Access Denied" Exception

- rod/component/clipping_rect_component.nim
- rod/node.nim
- rod/tools/serializer.nim
clipping rect component serialization
don't serialize empty childrens and components in node 
@rrenderr
> clipping rect component serialization

- rod/component/ae_composition.nim
- rod/edit_view.nim
> Fix meta animation

- rod/component/ae_composition.nim
- rod/property_editors/standard_editors.nim
> - added AEanimation standard editor

- after_effects_export/rod_export.nim
- rod/component/ae_composition.nim
- rod/component/particle_system.nim
- rod/property_editors/standard_editors.nim
- remove debug play from AEAnimation 
- added start rotation for particles
- fix texts with bounds export from AE
> AE text export fixes

- rod/edit_view.nim
- rod/editor/animation_chart_view.nim
- rod/editor_camera_controller.nim
remove deprecated event handler's code
> remove deprecated code

- rod/asset_bundle.nim
- rod/component/particle_emitter.nim
add onParticleUpdate callback
change particledata visibility
fix oneShot particle emitted count
> Particle emitter changes

- rod/edit_view.nim
- rod/editor/editor_tree_view.nim
fixed selection in outlineview after ray-casting node
better toggleEditTab remove logic after drugging tabs
> Fix editor select

- rod/asset_bundle.nim
> Fix bundle downloading

- rod/editor/file_system/editor_asset_icon_view.nim
> Fix image icon view

- rod/editor/file_system/editor_asset_icon_view.nim
The commits are independent. Should be reviewed separately.
> Fix asset icon
